{% set name = "intake-sqlite" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-sqlite-{{ version }}.tar.gz
  sha256: 4084e3f3910b5b004e4ba87479caf13769abb903e355b4ec994e9cbb5b33e886

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - setuptools-scm
  run:
    - fsspec <2022.6.0
    - intake <=0.6.5
    - intake-sql <=0.3.1
    - pandas <=1.4.2
    - python >=3.8,<3.11
    - sqlalchemy <=1.4.36

test:
  imports:
    - intake_sqlite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/intake-sqlite
  summary: An Intake driver to access local or remote SQLite databases by URL.
  dev_url: https://github.com/catalyst-cooperative/intake-sqlite
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zaneselvans
