{% set name = "intake-sqlite" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-sqlite-{{ version }}.tar.gz
  sha256: f4d130ea5405440e19d899d2f323a94dacab5662beb12feadda1f6f4355801e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - setuptools-scm
  run:
    - fsspec >=2022.5,<2023
    - intake-sql >=0.3.1,<0.4
    - python >=3.8,<3.11

test:
  imports:
    - intake_sqlite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/intake-sqlite
  summary: An Intake driver to access local or remote SQLite databases by URL.
  dev_url: https://github.com/catalyst-cooperative/intake-sqlite
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zaneselvans
